### ISSUE TITLE
Put back go.yml file which is intended to run after each push

### ISSUE THREAD

**Issue by Envoy49** [Envoy49/go-spotify-cli#9]
This part is consuming a lot of time from actions and consequently introduces additional cost.
If this project has more contributors and grows in demand then we need funding.
So we can run checks on each commit.

Good starting point I had before but removed these actions because of cost.

```
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test on Go ${{ matrix.go }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
```
